package pt.isel.pdm.chess4android.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class ChallengeInfo( //the "id" is generated by the firebase (it's a hash), the rest is inputed by the user
    val id: String,
    val challengerName: String,
    val challengerMessage: String
) : Parcelable